name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.0]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        sudo apt-get update
        sudo apt install -y libusb-1.0-0-dev
        npm install node-gyp --force
        npm install --force
        npm install -g grunt-cli
        npm install --save-dev grunt-cli
        grunt
